# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/
name: OSV-Scanner-opt

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  osv-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OSV-Scanner
        uses: google/osv-scanner-action/setup-osv-scanner@v2

      - name: Run OSV-Scanner
        run: |
          osv-scanner scan \
            -r \
            --skip-git \
            --format sarif \
            --output osv-results.sarif \
            . || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: osv-results.sarif
